#!/bin/bash

WEB_SERVICE=http://petric.esy.es/

# ./easyscp <username> <domain> <source> <destination>
# ./easyscp jean jeanpetric :~/file.pdf .

username=$1
domain=$2
src=$3
dest=$4

if [ "$#" -ne 4 ]; then
  echo "usage: ./easyscp <username> <domain> <source> <destination>"
  exit
fi

url=$(wget $WEB_SERVICE$2 -q -O -)

scp $username@$url$src $dest
